export const BADGELOTTRYTIMESTR = '2023-10-29 12:00:00';
export const SCROLLEVENTNAME = 'SCROLL_LAUNCH_CAMPAIGN';
export const BASEVENTNAME = 'BAS_EVENT_PROOF_OF_HUMANITY';
export const LINEAEVENTNAME = 'LINEA_DEFI_VOYAGE';
export const LUCKYDRAWEVENTNAME = 'PRODUCT_DEBUT';
export const EARLYBIRDNFTEVENTNAME = 'EARLY_BIRD_NFT';
export const ETHSIGNEVENTNAME = 'SIGNX_X_PROGRAM';
export const EVENTNAMEMAP = {
  [ETHSIGNEVENTNAME]: 'SignX Program',
  [BASEVENTNAME]: 'BAS Event',
  [LINEAEVENTNAME]: 'Linea Voyage',
  [SCROLLEVENTNAME]: 'Scroll Attestation',
  [LUCKYDRAWEVENTNAME]: 'Lucky Draw',
  [EARLYBIRDNFTEVENTNAME]: 'Early Bird NFT',
};
